package controller.command;

/**
 *
 * Enum constants for available commands
 *
 */
public enum CommandName {
    CHANGE_LOCALE, SIGN_IN, LOGIN,
    REGISTRATION, SIGN_OUT, SHOW,
    MAIN_PAGE, SHOW_VACANCIES, SHOW_APPLICANTS,
    DELETE_VACANCY, ADMIN_REGISTRATION, ADD_VACANCY,
    REDIRECT, SUBMIT_APPLICATION, SEARCH_APPLICANT,
    SHOW_VACANCY, ADD_ADMIN, SHOW_ADMINS,
    ADD_INTERVIEW,ADD_PRE_INTERVIEW, ADD_TEC_INTERVIEW,
    UPDATE_APPLICANT, SEARCH_VACANCY, UPDATE_ADMIN,
    GET_APPLICANT, DELETE_APPLICATION, ADD_NEWS,
    TAKE_TECHNOLOGIES, ADD_SKILL, TAKE_NEWS,
    SEARCH_NEWS, DELETE_NEWS, GET_NEWS, WRONG_REQUEST
}
